language: generic
sudo: required

install:
  - |
    echo "installing miniconda"
    rm -rf $HOME/miniconda
    mkdir -p $HOME/download
    curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o $HOME/download/miniconda.sh
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda

    export PATH=$HOME/miniconda/bin:$PATH

    conda config --set always_yes yes --set changeps1 no
    conda config --add channels defaults
    conda config --add channels conda-forge
    conda update -q conda
    conda info -a

    conda create -q -n test-env \
        git \
        python=3.7 \
        pip \
        tini \
        pygithub \
        tenacity \
        requests \
        ruamel.yaml \
        flake8 \
        pytest

    source activate test-env

    pip install --no-deps -e .

script:
  - flake8 conda_forge_tick_action
  - pytest -vv conda_forge_tick_action
  - command -v run-regro-cf-autotick-bot-action
