name: 'automerge-action'
description: 'regro-cf-autotick-bot GitHub Action'
author: conda-forge core (@conda-forge/core)
inputs:
  github_token:
    description: 'github token'
    required: true
runs:
  using: 'docker'
  image: 'docker://condaforge/automerge-action:dev'
  args:
    - ${{ inputs.github_token }}
