name: 'automerge-action'
description: 'conda-forge automerge GitHub Action'
author: conda-forge core (@conda-forge/core)
inputs:
  github_token:
    description: 'github token'
    required: true
  rerendering_github_token:
    description: 'github token for rerendering'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://condaforge/automerge-action:dev'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.rerendering_github_token }}
