#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

git config --global user.name "conda-forge-webservices[bot]"
git config --global user.email "91080706+conda-forge-webservices[bot]@users.noreply.github.com"

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

run-automerge-action
