#!/usr/bin/env sh

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

git config --global user.name "conda-forge-webservices[bot]"
git config --global user.email "91080706+conda-forge-webservices[bot]@users.noreply.github.com"

run-automerge-action
