#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

git config --global user.name ${GITHUB_ACTOR}
git config --global user.email "github-actions@email.com"

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

run-regro-cf-autotick-bot-action
