name: tests

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "0 6 * * SUN" # Once weekly on Sunday @ 0600 UTC
  workflow_dispatch: null

concurrency:
  group: ${{ github.workflow }}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          python-version: "3.11"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yml

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda info -a

          mamba install pytest conda-smithy

          pip install --no-deps -e .

      - name: lint and run tests
        shell: bash -l {0}
        run: |
          pytest -vv conda_forge_automerge_action
          command -v run-automerge-action

      - name: generate token
        id: generate_token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1
        with:
          app-id: ${{ secrets.CF_CURATOR_APP_ID }}
          private-key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: run live tests
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python live_tests/run_automerge_live_tests.py --build-and-push
        env:
          GHA_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.CF_BOT_DH_PASSWORD }}

  docker-push:
    name: docker-push
    runs-on: "ubuntu-latest"
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          username: condaforgebot
          password: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          push: true
          tags: condaforge/automerge-action:prod

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: condaforgebot
          DOCKER_PASS: ${{ secrets.CF_BOT_DH_PASSWORD }}
        with:
          destination_container_repo: condaforge/automerge-action:prod
          provider: dockerhub
          short_description: "conda-forge image used to power the bot automerge GitHub Actions integration"
          readme_file: "Dockerfile_README.md"
