name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda info -a

          mamba install \
            git \
            python=3.11 \
            pip \
            tini \
            pygithub \
            tenacity \
            requests \
            ruamel.yaml \
            flake8 \
            pytest

          pip install --no-deps -e .

      - name: lint and run tests
        shell: bash -l {0}
        run: |
          pytest -vv conda_forge_automerge_action
          command -v run-automerge-action

      - name: build the docker image
        shell: bash -l {0}
        run: |
          docker build --no-cache -t test .
