name: tests

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC
  workflow_dispatch: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yml

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda info -a

          mamba install pytest

          pip install --no-deps -e .

      - name: lint and run tests
        shell: bash -l {0}
        run: |
          pytest -vv conda_forge_automerge_action
          command -v run-automerge-action

      - name: build the docker image
        shell: bash -l {0}
        run: |
          docker build --no-cache -t test .

  docker-push:
    name: docker-push
    runs-on: "ubuntu-latest"
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: condaforgebot
          password: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: condaforge/automerge-action:prod
